# backend/app/models/enums.py
from enum import Enum as PyEnum


class CertificateStatus(str, PyEnum):
    EN_PROCESO = "EN_PROCESO"
    FALTA_TAREAS = "FALTA_TAREAS"
    NO_CONCLUYO = "NO_CONCLUYO"
    LISTO_PARA_DESCARGAR = "LISTO_PARA_DESCARGAR"
    REVOCADO = "REVOCADO"

class CertificateKind(str, PyEnum):
    PILDORA_PARTICIPANTE = "PILDORA_PARTICIPANTE"
    PILDORA_PONENTE = "PILDORA_PONENTE"
    INYECCION_PARTICIPANTE = "INYECCION_PARTICIPANTE"
    INYECCION_PONENTE = "INYECCION_PONENTE"
    CURSO_PARTICIPANTE = "CURSO_PARTICIPANTE"
    CURSO_PONENTE = "CURSO_PONENTE"
    CURSO_COMPETENCIAS_PARTICIPANTE = "CURSO_COMPETENCIAS_PARTICIPANTE"
    CURSO_COMPETENCIAS_PONENTE = "CURSO_COMPETENCIAS_PONENTE"

class CourseType(str, PyEnum):
    PILDORA_EDUCATIVA = "PILDORA_EDUCATIVA"
    INYECCION_EDUCATIVA = "INYECCION_EDUCATIVA"
    CURSO_EDUCATIVO = "CURSO_EDUCATIVO"

class CourseModality(str, PyEnum):
    REMOTA = "REMOTA"
    PRESENCIAL = "PRESENCIAL"
    HIBRIDA = "HIBRIDA"